sudo: required
language: ruby
services:
  - docker
rvm:
  - jruby-9.1.15.0
  - 2.1.9
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_master.gemfile
bundler_args: --without local
before_install:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker-compose up -d
  - gem install bundler -v '> 1.5.0'
env:
  RUBY_GC_MALLOC_LIMIT: 90000000
  RUBY_GC_HEAP_FREE_SLOTS: 200000
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_master.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/rails_5_0.gemfile
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_master.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/rails_master.gemfile
  fast_finish: true
cache: bundler

notifications:
  slack: shyftplanteam:ytcBo8O4FsF6i11yzoCmfvTU
